### PR TITLE
Changed Makefile for non source-based distros

### PR DESCRIPTION
**Pull request by bazarassa**

### CODE REVIEW

**Comment by l29ah** [comment]
The Makefile should use `$PREFIX` instead of hard-coding the path. Also you haven't specified deps for `install` target.

**Comment by bazarassa** [comment]
I don't know, why do you want from me to declare another var, whether Makefile could do all suggested things for installment, and to things that package manager must do (dealing with dependencies).

Or you meant installation of `test` file in `$PATH`, e.g. `/usr/local`?

**Comment by l29ah** [comment]
Because different distros install libraries under different paths (and no sane package manager installs stuff under /usr/local, by the way).
No, tests shouldn't be built and installed by an end user.

**Comment by bazarassa** [comment]
Ok, got it.

**Comment by Voker57** [comment]
> The Makefile should use `$PREFIX` instead of hard-coding the path. Also you haven't specified deps for `install` target.

consider relying on using install(1) with https://asic-linux.com.mx/~izto/checkinstall/installwatch.html instead of some kludge envvars

**Comment by l29ah** [comment]
I do use install(1) and it doesn't specify any paths itself. Your link is irrelevant as i don't want to limit myself with a concrete package management system.

**Pull request closed without merging**
